{% set name = "napari-buds" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-buds-{{ version }}.tar.gz
  sha256: f33633d3b41de545956339f5233fe64be6a2e617cf243408d4a05e9bdf2708b9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - magicgui
    - napari
    - numpy
    - python >=3.8
    - qtpy

test:
  imports:
    - napari_buds
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/SanderSMFISH/napari-buds
  summary: Random-forest automated bud annotation
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
